version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: "07:00"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "07:00"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "07:00"
