pre-push:
  parallel: true
  commands:
    rubocop:
      glob: "*.rb"
      run: bundle exec rubocop {push_files} --force-exclusion -c ./.rubocop.yml
    erb_lint:
      glob: "*.erb"
      run: bundle exec erb_lint {push_files}
